export const GET_SATELLITE_LOCATION = 'GET_SATELLITE_LOCATION';
export const GET_SATELLITE_PEOPLE = 'GET_SATELLITE_PEOPLE';
export const GET_NASA_PHOTO = 'GET_NASA_PHOTO';
export const NASA_PHOTO_API_KEY='s1I8lIFQCSobZinJXcd4n8ebWD972Az36gTON57p';